import SwiftUI

struct TranslateSheet: View {
    @Binding var note: RecordNote
    let patient: Patient
    let onSave: (RecordNote) -> Void

    @Environment(\.dismiss) private var dismiss

    enum TargetLanguage: String, CaseIterable {
        // Arabic first
        case arabic = "Arabic"
        // European
        case french = "French"
        case spanish = "Spanish"
        case german = "German"
        case italian = "Italian"
        case portuguese = "Portuguese"
        case russian = "Russian"
        case turkish = "Turkish"
        // Asian
        case chinese = "Chinese (Simplified)"
        case japanese = "Japanese"
        case korean = "Korean"
        case hindi = "Hindi"
        case urdu = "Urdu"

        var nativeName: String {
            switch self {
            case .arabic: return "العربية"
            case .french: return "Fran\u{00E7}ais"
            case .spanish: return "Espa\u{00F1}ol"
            case .german: return "Deutsch"
            case .italian: return "Italiano"
            case .portuguese: return "Portugu\u{00EA}s"
            case .russian: return "Русский"
            case .turkish: return "T\u{00FC}rk\u{00E7}e"
            case .chinese: return "中文"
            case .japanese: return "日本語"
            case .korean: return "한국어"
            case .hindi: return "हिन्दी"
            case .urdu: return "اردو"
            }
        }
    }

    @State private var selectedLanguage: TargetLanguage = .arabic
    @State private var translatedText: String = ""
    @State private var isLoading = false
    @State private var errorMessage: String = ""
    private let disclaimer_en = "** This translation was generated by AI and has not been verified by a certified medical translator. **"

    private var isRTLLanguage: Bool {
        selectedLanguage == .arabic || selectedLanguage == .urdu
    }

    private var disclaimer_target: String {
        switch selectedLanguage {
        case .arabic: return "** هذه الترجمة تم إنشاؤها بواسطة الذكاء الاصطناعي ولم يتم التحقق منها من قبل مترجم طبي معتمد. **"
        case .french: return "** Cette traduction a \u{00E9}t\u{00E9} g\u{00E9}n\u{00E9}r\u{00E9}e par IA et n'a pas \u{00E9}t\u{00E9} v\u{00E9}rifi\u{00E9}e par un traducteur m\u{00E9}dical certifi\u{00E9}. **"
        case .spanish: return "** Esta traducci\u{00F3}n fue generada por IA y no ha sido verificada por un traductor m\u{00E9}dico certificado. **"
        case .german: return "** Diese \u{00DC}bersetzung wurde von KI erstellt und nicht von einem zertifizierten medizinischen \u{00DC}bersetzer \u{00FC}berpr\u{00FC}ft. **"
        default: return disclaimer_en
        }
    }

    var body: some View {
        NavigationStack {
            VStack(spacing: 0) {
                // Language picker
                VStack(spacing: 8) {
                    Text("Translate To").font(.caption).foregroundStyle(.secondary)
                    Picker("Language", selection: $selectedLanguage) {
                        ForEach(TargetLanguage.allCases, id: \.self) { lang in
                            Text("\(lang.rawValue) (\(lang.nativeName))").tag(lang)
                        }
                    }
                    #if os(iOS)
                    .pickerStyle(.wheel)
                    .frame(height: 120)
                    #else
                    .pickerStyle(.menu)
                    #endif
                }
                .padding()

                Divider()

                ScrollView {
                    VStack(alignment: .leading, spacing: 16) {
                        // Source preview
                        VStack(alignment: .leading, spacing: 6) {
                            Text("Original Note").font(.caption).foregroundStyle(.secondary)
                            Text(note.body.prefix(300) + (note.body.count > 300 ? "..." : ""))
                                .font(.caption2)
                                .foregroundStyle(.secondary)
                                .padding(10)
                                .frame(maxWidth: .infinity, alignment: .leading)
                                .background(Color.tertiarySystemGroupedBg)
                                .clipShape(RoundedRectangle(cornerRadius: 8))
                        }

                        // Translate button
                        Button {
                            Task { await translateNote() }
                        } label: {
                            HStack {
                                if isLoading {
                                    ProgressView().tint(.white)
                                } else {
                                    Image(systemName: "globe")
                                }
                                Text(isLoading ? "Translating..." : "Translate to \(selectedLanguage.rawValue)")
                            }
                            .frame(maxWidth: .infinity)
                            .padding(.vertical, 10)
                        }
                        .buttonStyle(.borderedProminent)
                        .tint(.blue)
                        .disabled(isLoading || note.body.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty)

                        // Error
                        if !errorMessage.isEmpty {
                            HStack {
                                Image(systemName: "exclamationmark.triangle.fill").foregroundStyle(.red)
                                Text(errorMessage).font(.caption).foregroundStyle(.red)
                            }
                        }

                        // Translated result
                        if !translatedText.isEmpty {
                            VStack(alignment: isRTLLanguage ? .trailing : .leading, spacing: 8) {
                                HStack {
                                    Text("Translation (\(selectedLanguage.rawValue))").font(.headline)
                                    Spacer()
                                    Button {
                                        translatedText = ""
                                        errorMessage = ""
                                    } label: {
                                        Label("Clear", systemImage: "xmark.circle")
                                            .font(.caption)
                                    }
                                    .buttonStyle(.bordered)
                                    .tint(.secondary)
                                }

                                // Translated text with RTL support
                                #if os(iOS)
                                TextEditor(text: .constant(translatedText))
                                    .font(.body)
                                    .frame(minHeight: 200)
                                    .environment(\.layoutDirection, isRTLLanguage ? .rightToLeft : .leftToRight)
                                    .multilineTextAlignment(isRTLLanguage ? .trailing : .leading)
                                    .padding(4)
                                    .background(Color.secondarySystemGroupedBg)
                                    .clipShape(RoundedRectangle(cornerRadius: 10))
                                #elseif os(macOS)
                                MacTranslationTextView(
                                    text: translatedText,
                                    isRTL: isRTLLanguage
                                )
                                .frame(minHeight: 200)
                                .clipShape(RoundedRectangle(cornerRadius: 10))
                                #endif

                                // Disclaimer preview
                                VStack(alignment: isRTLLanguage ? .trailing : .leading, spacing: 4) {
                                    Text(disclaimer_en)
                                        .font(.caption2).foregroundStyle(.orange)
                                    Text(disclaimer_target)
                                        .font(.caption2).foregroundStyle(.orange)
                                        .multilineTextAlignment(isRTLLanguage ? .trailing : .leading)
                                        .frame(maxWidth: .infinity, alignment: isRTLLanguage ? .trailing : .leading)
                                        .environment(\.layoutDirection, isRTLLanguage ? .rightToLeft : .leftToRight)
                                }
                                .padding(8)
                                .background(Color.orange.opacity(0.1))
                                .clipShape(RoundedRectangle(cornerRadius: 8))

                                // Action buttons
                                HStack(spacing: 12) {
                                    Button {
                                        addTranslationToNote()
                                    } label: {
                                        Label("Add to Note", systemImage: "plus.square.on.square")
                                            .frame(maxWidth: .infinity)
                                    }
                                    .buttonStyle(.borderedProminent)
                                    .tint(.blue)
                                    .disabled(note.isFinalized)

                                    Button {
                                        PlatformPasteboard.copy(translatedText)
                                    } label: {
                                        Label("Copy", systemImage: "doc.on.doc")
                                            .frame(maxWidth: .infinity)
                                    }
                                    .buttonStyle(.bordered)
                                }
                            }
                        }
                    }
                    .padding()
                }
            }
            .navigationTitle("Translate")
            .inlineNavigationTitle()
            .toolbar {
                ToolbarItem(placement: .cancellationAction) {
                    Button("Done") { dismiss() }
                }
            }
        }
    }

    // MARK: - Translation Logic

    private func translateNote() async {
        isLoading = true
        errorMessage = ""

        do {
            let system = """
            You are a professional medical translator. Translate the following clinical note \
            to \(selectedLanguage.rawValue). Maintain medical terminology accuracy. \
            Preserve the structure and formatting of the original note. \
            Output ONLY the translated text, no preamble or explanation.
            """
            let result = try await ClaudeService.shared.generate(
                system: system,
                userMessage: "Translate this clinical note to \(selectedLanguage.rawValue):\n\n\(note.body)",
                maxTokens: 3000
            )

            await MainActor.run {
                translatedText = result
            }
        } catch {
            await MainActor.run {
                errorMessage = error.localizedDescription
            }
        }

        await MainActor.run {
            isLoading = false
        }
    }

    private func addTranslationToNote() {
        guard !note.isFinalized else { return }
        let separator = "\n\n" + String(repeating: "\u{2500}", count: 40) + "\n"
        let block = separator
            + "TRANSLATION (\(selectedLanguage.rawValue.uppercased()))\n"
            + disclaimer_en + "\n"
            + disclaimer_target + "\n\n"
            + translatedText + "\n"
        note.body += block
        onSave(note)
    }
}

// MARK: - macOS Native RTL Text View
#if os(macOS)
import AppKit

struct MacTranslationTextView: NSViewRepresentable {
    let text: String
    let isRTL: Bool

    func makeNSView(context: Context) -> NSScrollView {
        let scrollView = NSTextView.scrollableTextView()
        let textView = scrollView.documentView as! NSTextView
        textView.isEditable = false
        textView.isSelectable = true
        textView.font = NSFont.systemFont(ofSize: 14)
        textView.textContainer?.widthTracksTextView = true
        textView.drawsBackground = true
        textView.backgroundColor = NSColor.controlBackgroundColor
        return scrollView
    }

    func updateNSView(_ scrollView: NSScrollView, context: Context) {
        guard let textView = scrollView.documentView as? NSTextView else { return }
        textView.string = text
        if isRTL {
            textView.alignment = .right
            textView.setBaseWritingDirection(.rightToLeft,
                range: NSRange(location: 0, length: (text as NSString).length))
        } else {
            textView.alignment = .left
            textView.setBaseWritingDirection(.leftToRight,
                range: NSRange(location: 0, length: (text as NSString).length))
        }
    }
}
#endif
